repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
    -   id: ruff
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.33.0
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django