version: "3.9"
services:
  db-visits:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5437:5432"
    networks:
      - mc_network
  web-visits:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8600
    volumes:
      - ./src:/app/src
    ports:
      - "8600:8600"
    networks:
      - mc_network
    depends_on:
      - db-visits
networks:
  mc_network:
    external: true