# Generated by Django 5.1 on 2025-04-12 08:53

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
