# Generated by Django 5.1 on 2024-10-13 19:40

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='visit',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
