# Generated by Django 5.1 on 2024-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_visit_managers_visit_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
