# Generated by Django 5.1 on 2025-03-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_availabilities', '0002_doctoravailability_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor_id',
            field=models.CharField(max_length=50),
        ),
    ]
