# Generated by Django 5.1 on 2025-03-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_availabilities', '0003_alter_doctoravailability_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
